name: CI/CD Pipeline - Python to Azure

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest  # or your preferred test command

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name figfigacr

      - name: Build Docker Image
        run: |
          docker build -t figfigacr.azurecr.io/figfig-app:${{ github.sha }} .

      - name: Push Docker Image to ACR
        run: |
          docker push figfigacr.azurecr.io/figfig-app:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-webapp-name>
          images: figfigacr.azurecr.io/figfig-app:${{ github.sha }}
