name: Force Unlock Terraform

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: "Terraform Lock ID (copy from error log)"
        required: true


permissions:
  id-token: write
  contents: read


jobs:
  force-unlock:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        run: terraform init -backend-config="envs/dev/backend.tf"

      - name: Force unlock state
        run: terraform force-unlock -force ${{ github.event.inputs.lock_id }}
