name: Prod Deployment

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # auth-type: IDENTITY
          enable-AzPSSession: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: Terraform Init + Apply
        working-directory: terraform
        run: |
          terraform init -backend-config="envs/prod/backend.tf"
          terraform apply -lock-timeout=60s -auto-approve -var-file="envs/prod/terraform.tfvars"

      - name: Docker Login to ACR using Azure CLI
        run: |
          az acr login --name figfigacrprod

      - name: Build Docker Image
        run: |
          docker build -f docker/Dockerfile --build-arg ENV=prod -t figfigacrprod.azurecr.io/figfig-app:pro .

      - name: Push Docker Image
        run: |
          docker push figfigacrprod.azurecr.io/figfig-app:prod
 